=begin
#virusapi

#The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveVirusScanApiClient::AdditionalAdvancedScanInformation
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AdditionalAdvancedScanInformation' do
  before do
    # run before each test
    @instance = CloudmersiveVirusScanApiClient::AdditionalAdvancedScanInformation.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AdditionalAdvancedScanInformation' do
    it 'should create an instance of AdditionalAdvancedScanInformation' do
      expect(@instance).to be_instance_of(CloudmersiveVirusScanApiClient::AdditionalAdvancedScanInformation)
    end
  end
  describe 'test attribute "contains_json"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "contains_xml"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
