=begin
#virusapi

#Virus API lets you scan files and content for viruses and identify security issues with content.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveVirusScanApiClient::VirusFound
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VirusFound' do
  before do
    # run before each test
    @instance = CloudmersiveVirusScanApiClient::VirusFound.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VirusFound' do
    it 'should create an instance of VirusFound' do
      expect(@instance).to be_instance_of(CloudmersiveVirusScanApiClient::VirusFound)
    end
  end
  describe 'test attribute "file_name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "virus_name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

