=begin
#virusapi

#The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveVirusScanApiClient::WebsiteScanRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WebsiteScanRequest' do
  before do
    # run before each test
    @instance = CloudmersiveVirusScanApiClient::WebsiteScanRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebsiteScanRequest' do
    it 'should create an instance of WebsiteScanRequest' do
      expect(@instance).to be_instance_of(CloudmersiveVirusScanApiClient::WebsiteScanRequest)
    end
  end
  describe 'test attribute "url"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

