=begin
#virusapi

#Virus API lets you scan files and content for viruses and identify security issues with content.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

module CloudmersiveVirusScanApiClient
  VERSION = "1.3.0"
end
