=begin
#virusapi

#The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveVirusScanApiClient::ScanCloudStorageApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ScanCloudStorageApi' do
  before do
    # run before each test
    @instance = CloudmersiveVirusScanApiClient::ScanCloudStorageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ScanCloudStorageApi' do
    it 'should create an instance of ScanCloudStorageApi' do
      expect(@instance).to be_instance_of(CloudmersiveVirusScanApiClient::ScanCloudStorageApi)
    end
  end

  # unit tests for scan_cloud_storage_scan_aws_s3_file
  # Scan an AWS S3 file for viruses
  # Scan the contents of a single AWS S3 file and its content for viruses. Leverage continuously updated signatures for millions of threats, and advanced high-performance scanning capabilities.  Over 17 million virus and malware signatures.  Continuous cloud-based updates.  Wide file format support including Office, PDF, HTML, Flash.  Zip support including .Zip, .Rar, .DMG, .Tar, and other archive formats.  Multi-threat scanning across viruses, malware, trojans, ransomware, and spyware.  High-speed in-memory scanning delivers subsecond typical response time.
  # @param access_key AWS S3 access key for the S3 bucket; you can get this from My Security Credentials in the AWS console
  # @param secret_key AWS S3 secret key for the S3 bucket; you can get this from My Security Credentials in the AWS console
  # @param bucket_region Name of the region of the S3 bucket, such as &#39;US-East-1&#39;
  # @param bucket_name Name of the S3 bucket
  # @param key_name Key name (also called file name) of the file in S3 that you wish to scan for viruses
  # @param [Hash] opts the optional parameters
  # @return [CloudStorageVirusScanResult]
  describe 'scan_cloud_storage_scan_aws_s3_file test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for scan_cloud_storage_scan_azure_blob
  # Scan an Azure Blob for viruses
  # Scan the contents of a single Azure Blob and its content for viruses. Leverage continuously updated signatures for millions of threats, and advanced high-performance scanning capabilities.  Over 17 million virus and malware signatures.  Continuous cloud-based updates.  Wide file format support including Office, PDF, HTML, Flash.  Zip support including .Zip, .Rar, .DMG, .Tar, and other archive formats.  Multi-threat scanning across viruses, malware, trojans, ransomware, and spyware.  High-speed in-memory scanning delivers subsecond typical response time.
  # @param connection_string Connection string for the Azure Blob Storage Account; you can get this connection string from the Access Keys tab of the Storage Account blade in the Azure Portal.
  # @param container_name Name of the Blob container within the Azure Blob Storage account
  # @param blob_path Path to the blob within the container, such as &#39;hello.pdf&#39; or &#39;/folder/subfolder/world.pdf&#39;
  # @param [Hash] opts the optional parameters
  # @return [CloudStorageVirusScanResult]
  describe 'scan_cloud_storage_scan_azure_blob test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for scan_cloud_storage_scan_gcp_storage_file
  # Scan an Google Cloud Platform (GCP) Storage file for viruses
  # Scan the contents of a single Google Cloud Platform (GCP) Storage file and its content for viruses. Leverage continuously updated signatures for millions of threats, and advanced high-performance scanning capabilities.  Over 17 million virus and malware signatures.  Continuous cloud-based updates.  Wide file format support including Office, PDF, HTML, Flash.  Zip support including .Zip, .Rar, .DMG, .Tar, and other archive formats.  Multi-threat scanning across viruses, malware, trojans, ransomware, and spyware.  High-speed in-memory scanning delivers subsecond typical response time.
  # @param bucket_name Name of the bucket in Google Cloud Storage
  # @param object_name Name of the object or file in Google Cloud Storage
  # @param json_credential_file Service Account credential for Google Cloud stored in a JSON file.
  # @param [Hash] opts the optional parameters
  # @return [CloudStorageVirusScanResult]
  describe 'scan_cloud_storage_scan_gcp_storage_file test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
