=begin
#virusapi

#Virus API lets you scan files and content for viruses and identify security issues with content.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for CloudmersiveVirusScanApiClient::ScanApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ScanApi' do
  before do
    # run before each test
    @instance = CloudmersiveVirusScanApiClient::ScanApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ScanApi' do
    it 'should create an instance of ScanApi' do
      expect(@instance).to be_instance_of(CloudmersiveVirusScanApiClient::ScanApi)
    end
  end

  # unit tests for scan_file
  # Scan a file for viruses
  # 
  # @param input_file Input file to perform the operation on.
  # @param [Hash] opts the optional parameters
  # @return [VirusScanResult]
  describe 'scan_file test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for scan_website
  # Scan a website for malicious content including viruses and threats (including Phishing)
  # 
  # @param input 
  # @param [Hash] opts the optional parameters
  # @return [WebsiteScanResult]
  describe 'scan_website test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
